#exec-once = $terminal
#exec-once = hyprpaper
exec-once = waybar

# scipts
exec-once = /home/linus/.config/hypr/scripts/auto_change_wallpaper_DP-1.sh
exec-once = /home/linus/.config/hypr/scripts/auto_change_wallpaper_DP-2.sh
exec-once = /home/linus/.config/hypr/scripts/auto_change_wallpaper_HDMI-A-1.sh
