exec-once = waybar

exec-once = swww-daemon
exec-once = ~/.config/hypr/scripts/auto_change_wallpaper.sh ~/Documents/wallpapers/3440x1440 DP-2 900 5400
exec-once = ~/.config/hypr/scripts/auto_change_wallpaper.sh ~/Documents/wallpapers/2160x3840 DP-1 900 5400
exec-once = ~/.config/hypr/scripts/auto_change_wallpaper.sh ~/Documents/wallpapers/2160x3840 HDMI-A-1 900 5400
